server:
  port: 8081

spring:
  application:
    name: gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

routes:
  - id: user-service
    uri: lb://user-service
    predicates:
      - Path=/api/users/**, /api/auth/**