server:
  port: 8082

spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/user_service
    username: user_service_user
    password: "user_service_password"
  data:
    jdbc:
      dialect: mysql

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
